export const SET_CONNECTION = "SET_CONNECTION";
export const SET_QUERY = "SET_QUERY";
export const SET_ENTITY = "SET_ENTITY";
export const SET_ACTIVEFORM = "SET_ACTIVEFORM";
export const SET_LINKS = "SET_LINKS";
export const LAUNCH_MCS = "LAUNCH_MCS";
export const SET_ERROR = "SET_ERROR";
export const SET_VALIDATIONS = "SET_VALIDATIONS";
export const SET_SNACKBAR = "SET_SNACKBAR";
export const SET_LDAPUPDATED = "SET_LDAPUPDATED";
export const SET_DRAWER_STATE = "SET_DRAWER_STATE";

export const SNACKBAR_STATUS = { SUCCESS: "SUCCESS", WARNING: "WARNING" };
